config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 devise_for :users
 resources :recipes

 root "recipes#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

has_many :ingredients
has_many :directions
belongs_to :user

accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

validates :title, :description, :image, presence: true

has_attached_file :image, styles: { medium: "400x400>", thumb: "200x200>"}
validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def show
  end

  def index
    @recipe = Recipe.all.order("created_at DESC")
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: "Successfully created new recipe"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to root_path, notice: "Successfully Deleted"
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name , :_destroy], directions_attributes: [:id, :step, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
!!!
%html
%head
 %title Abhijit's Recipe Box
 = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
 %link{href: "https://fonts.googleapis.com/css?family=Lato" , rel: "stylesheet"}
 %link{href: "https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css" , rel: "stylesheet"}
 = javascript_include_tag 'application', 'data-turbolinks-track' => true
 = csrf_meta_tags
%body
 %header.main_header.clearfix
  .wrapper
   #logo
    %p= link_to "Abhijit's Recipe Box", root_path
   #buttons
    - if user_signed_in?
     = link_to "New Recipe", new_recipe_path
     = link_to "Logout", destroy_user_session_path, method: :delete
    - else
     = link_to "Sign up", new_user_registration_path
     = link_to "Sign in", new_user_session_path
.wrapper
 %p.notice= notice
 %p.alert= alert

 .wrapper
 = yield

app/views/layouts/application.html.haml
!!! 5
%html
%head
 %title Abhijit's Recipe Box
 = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
 %link{href: "https://fonts.googleapis.com/css?family=Lato" , rel: "stylesheet"}
 %link{href: "https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css" , rel: "stylesheet"}
 = javascript_include_tag 'application', 'data-turbolinks-track' => true
 = csrf_meta_tags
%body
 %header.main_header.clearfix
  .wrapper
   #logo
    %p= link_to "Abhijit's Recipe Box", root_path
   #buttons
    - if user_signed_in?
     = link_to "New Recipe", new_recipe_path
     = link_to "Logout", destroy_user_session_path, method: :delete
    - else
     = link_to "Sign up", new_user_registration_path
     = link_to "Sign in", new_user_session_path
 .wrapper
  %p.notice= notice
  %p.alert= alert

 .container
  = yield

app/views/recipes/_direction_fields.html.haml
.nested-fields
 = f.input :step, input_html: {class: 'form-control'}
 .links
  = link_to_remove_association "remove direction", f, class: "btn-tasks"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: {multipart: true} do |f|
 - if @recipe.errors.any?
  #errors
   %p
    = @recipe.errors.count
    Prevented this recipe from saving
   %ul
    - @recipe.errors.full_messages.each do |msg|
     %li= msg
 .panel-body
  = f.input :title, input_html: {class: 'form-control'}
  = f.input :description, input_html: {class: 'form-control'}
  = f.input :image , as: :file, input_html: {class: 'form-control'}
 .row
  .col-md-6
   %h3 Ingredients
   #ingredients
    = f.simple_fields_for :ingredients do |ingredient|
     = render 'ingredient_fields', f: ingredient
    .links
     = link_to_add_association 'add ingredient', f, :ingredients, class: "btn-tasks"
  .col-md-6
   %h3 Directions
   #directions
    = f.simple_fields_for :directions do |direction|
     = render 'direction_fields', f: direction
    .links
     = link_to_add_association 'add direction', f, :directions, class: "btn-tasks"
 %br/
 %hr/
 = f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
.nested-fields
 = f.input :name, input_html: {class: 'form-control'}
 .links
  = link_to_remove_association "remove ingredient", f, class: "btn-tasks"

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.haml
%h1 Edit Recipe
= render 'form'

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
 .row
  - recipes.each do |recipe|
   .col-md-4
    .card
     .card-image
      = link_to recipe do
       = image_tag recipe.image.url(:medium)
     .card-block
      .card-title
       %h4= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New recipe

= render 'form'


#back-button
 = link_to "Back", root_path

app/views/recipes/show.html.haml
.main_content
 #recipe-top.row
  .col-md-4
   = image_tag @recipe.image.url(:medium), class: "recipe-image"
  .col-md-8
   #recipe-info
    %h1= @recipe.title
    %p= @recipe.description
    %p
     Submitted by
     = @recipe.user.email

 .row
  .col-md-6
   #ingredients
    %h2 Ingredients
    %ul
     - @recipe.ingredients.each do |ingredient|
      %li= ingredient.name

  .col-md-6
   #directions
    %h2 Directions
    %ul
     - @recipe.directions.each do |direction|
      %li= direction.step

 .row
  .col-md-12#back-button
   = link_to "Back", root_path
   - if user_signed_in?
    = link_to "Edit", edit_recipe_path
    = link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?"}

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>